Rogulike code
fedochet/roguelike pull request #2
Opened 2018-06-03 21:00 UTC by fedochet

2018-06-04 16:39 UTC, yurii-litvinov requested changes
С функциональностью всё хорошо. Надо только поправить обычные замечания по коду --- написать комментарии (хотя бы только к классам и интерфейсам, без методов) и хотя бы пару юнит-тестов

2018-06-04 16:39 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/roguelike/screens/PlayScreen.kt
> + * @return [this] if it is in range `[from, to]`, or closest to it value from range otherwise.
Ого, комментарий :)

2018-06-04 16:50 UTC, fedochet commented on src/main/kotlin/ru/spbau/mit/roguelike/screens/PlayScreen.kt
> + * @return [this] if it is in range `[from, to]`, or closest to it value from range otherwise.
@yurii-litvinov это одна из самых важных функций во всей кодовой базе :sweat_smile:

2018-06-09 11:12 UTC, yurii-litvinov requested changes
Надо ещё:
- Architectural drivers
- Роли и случаи использования
- Описание типичного пользователя

2018-06-09 11:12 UTC, yurii-litvinov commented on docs/readme.md
> +![Диаграмма компонентов](./components.png)
Диаграмме компонентов неплохо бы использовать стандартную нотацию UML, но поскольку тут это сводится просто к добавлению символа компонента, то можно не править

2018-06-09 11:12 UTC, yurii-litvinov commented on docs/readme.md
> +![Диаграмма потока экранов](./pla)
Тут не показывается, но вообще она ок

2018-06-09 11:12 UTC, yurii-litvinov commented on docs/readme.md
> +<!--![Sequence-diagram взаимодействия с игроком](./sequence.png)-->
Она нужна, да. И её, как я понял, вообще нет

2018-06-09 11:12 UTC, yurii-litvinov commented on docs/readme.md
> +![Классы для представления и управления персонажами](./characters-classes.png)
Для диаграмм классов требуется стандартная нотация UML всё-таки. С ключевыми полями и методами. И словесное описание хотя бы кратко.

2018-06-23 20:00 UTC, yurii-litvinov approved these changes
Комментариев и тестов всё равно маловато, но для конца сессии вполне норм. Зачтена

2018-06-23 20:05 UTC, fedochet commented
@yurii-litvinov спасибо!
Можно ли вас где-то поймать (в АУ или в Таймс), чтобы проставить зачет? Или это Тимофей может сделать?

2018-06-23 20:26 UTC, yurii-litvinov commented
Тимофей вполне может проставить, он вроде бывает в Таймс часто. Я пока ни в АУ, ни в Таймс не собирался, и вообще уезжаю на 4 дня завтра

2018-06-24 09:35 UTC, merged